//========== dialogs
export const COOKIE_LAW_DIALOG = "COOKIE_LAW_DIALOG";
export const EXPORT_GARDEN_AS_JSON_DIALOG = "EXPORT_GARDEN_AS_JSON_DIALOG";
export const IMPORT_FILE_SELECTOR_DIALOG = "IMPORT_FILE_SELECTOR_DIALOG";
export const OK_TO_RESET_DIALOG = "OK_TO_RESET_DIALOG";
export const ORDER_PLANT_LIST_DIALOG = "ORDER_PLANT_LIST_DIALOG";
export const PLANT_FICHE_DIALOG = "PLANT_FICHE_DIALOG";
export const PLANT_LIST_DIALOG = "PLANT_LIST_DIALOG";
export const NEW_PLANTS_DIALOG = "NEW_PLANTS_DIALOG";
export const SAVE_CAMERA_POSITION_DIALOG = "SAVE_CAMERA_POSITION_DIALOG";
export const SHOW_HIDE_DIALOG = "SHOW_HIDE_DIALOG";
export const TUTORIAL_DIALOG = "TUTORIAL_DIALOG";
